### ISSUE TITLE
My Braavos GOERLI account has been lost

### ISSUE THREAD

**Issue by Tekniktrader** [myBraavos/braavos-account-cairo#12]
My old valid account in Braavos wallet disappeared and a new account was created in its place.
This happened after I uninstalled and reinstalled my wallet.
My GOERLI address, which I cannot reach from my wallet, is on the chain: 
**0x03cfa7372e18b9e83adc88158aa88df5930976fa4eddb070bbe62da3a1316b1d**
This address has been replaced by a GOERLI address that I have never seen before:
**0x03ab98b9ff500a2d449023a7371554d041747ae2156728c3ee8d4345c602edb3**
I included proof that I had used the wallet before.
Can you offer a solution?
I can't understand what is the problem..

![br6](https://github.com/myBraavos/braavos-account-cairo/assets/114219988/45f7265a-e53a-49ee-b24f-d03793149a90)

**Comment by yoga-braavos** [comment]
If issue is still on-going, please reach out in our [Discord support channel](https://discord.com/channels/962985965889142844/964090590407053362)
