### ISSUE TITLE
New update has broken 2fa and 3fa. Bug report.

### ISSUE THREAD

**Issue by idvb188** [myBraavos/braavos-account-cairo#15]
Right after the new update was installed, the window for a second signer does not appear anymore. Moreover, I tryied to disable 3fa, waited for more than 96 hours, and nothing happend. It's been a week since I lost the opportunity to do anything in Braavos. I still cannot sigh any transaction, and I keep thinking my money will be locked in Braavos forever. 

I use Android (Samsung M) and Brave on my PC. 
The Brave extension is up to date, the Braavos wallet was updated as well. I tried to reinstall the extension, which did not work.

I was advised to disable the 2fa/3fa in Discord support; however, I could only click on 3fa in my extension when I was choosing what I want to disable. As a result, I now have 3fa enabled and 2fa disabled. I just could not request to disable them both. Now, I cannot disable the 3fa because of the error: 

```
RPC: starknet_estimateFee with params {
  "request": [
    {
      "type": "INVOKE",
      "sender_address": "0x949dfdc3d4e80674592feffb87a05ff76a5012169a781c5e6622b13412fe0",
      "calldata": [
        "0x1",
        "0x949dfdc3d4e80674592feffb87a05ff76a5012169a781c5e6622b13412fe0",
        "0x2a507ab0a32b1a7c2edf394ab941b06593c2a402a5f1a3b9ac3fcb62db0c01a",
        "0x0"
      ],
      "version": "0x100000000000000000000000000000001",
      "signature": [
        "0x1",
        "0x0",
        "0x0"
      ],
      "nonce": "0xfb",
      "max_fee": "0x0"
    }
  ],
  "block_id": "pending",
  "simulation_flags": [
    "SKIP_VALIDATE"
  ]
}
 
        41: Transaction execution error: {"execution_error":"Error in the called contract (0x000949dfdc3d4e80674592feffb87a05ff76a5012169a781c5e6622b13412fe0):\nError at pc=0:20259:\nGot an exception while executing a hint: Custom Hint Error: Execution failed. Failure reason: 0x494e56414c49445f454e545259504f494e54 ('INVALID_ENTRYPOINT').\nCairo traceback (most recent call last):\nUnknown location (pc=0:309)\nUnknown location (pc=0:5819)\nUnknown location (pc=0:11008)\n","transaction_index":0}
```

**Comment by yoga-braavos** [comment]
Hello @idvb188 , it is better to communicate such things over our Discord support channel. In any case I checked your account and 3FA should now be disabled:
![image](https://github.com/myBraavos/braavos-account-cairo/assets/103218450/83eddf41-0fb7-4883-ab62-d21c663b3e35)

It seems like you opened this issue prior to deferred removal being active. Please let us know in Discord if the problem persists.

**Comment by idvb188** [comment]
Yes, 

> Hello @idvb188 , it is better to communicate such things over our Discord support channel. In any case I checked your account and 3FA should now be disabled: ![image](https://private-user-images.githubusercontent.com/103218450/306613891-83eddf41-0fb7-4883-ab62-d21c663b3e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTgyNzksIm5iZiI6MTcwODUxNzk3OSwicGF0aCI6Ii8xMDMyMTg0NTAvMzA2NjEzODkxLTgzZWRkZjQxLTBmYjctNDg4My1hYjYyLWQyMWM2NjNiM2UzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxMjE5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWY0N2U2ZDk4ODM0NzcyY2U4NGEwMzc0NWMzMmZlOGVhNTRiNzMyYWIzMTcwYTAzYTQzM2ZjYmY0YmI5ZDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p81qndfgs7xGlyPfV2L4o5IgDhY8vj-rrcQOk-cQztY)
> 
> It seems like you opened this issue prior to deferred removal being active. Please let us know in Discord if the problem persists.

You think it is disabled? I don't think so: 
![image](https://github.com/myBraavos/braavos-account-cairo/assets/150317081/9e74216f-0787-416f-8577-b7bef07e39f4)

**Comment by idvb188** [comment]
@yoga-braavos would you comment on it?

**Comment by idvb188** [comment]
I don't think we can close the issue, since the problem was not solved. Nobody gives me an answer neither here, nor on the Discord. I do not even know whether developers know about the problem. It's been almost 2 weeks.
