### ISSUE TITLE
Disabling the 3fa entails an error. 

### ISSUE THREAD

**Issue by idvb188** [myBraavos/braavos-account-cairo#16]
I am trying to disable the 3fa from my extension. 

The story: 2 weeks ago, right after the new Cairo update, my 2fa was broken. The window for signing a transaction did not appear on my phone. I tried to reinstall everything (I did not know I should not do that). Moders on the Discord told me to disable the 2fa and 3fa. However, I could only choose one, only 3fa. I could not choose 2fa for disabling. So, I thought it was a 2 step process: 3fa first and 2fa can be disabled after that. The problem is after 4 days I saw that 2fa was disabled and 3fa was not. I am trying to disable the 3fa, but I see the error presented below. Since the previous issue I created was closed without even checking the problem, and since I do not have any reply yet in the Discord, I create a new issue. I rely on your competence. Thank you. 

RPC: starknet_estimateFee with params {
  "request": [
    {
      "type": "INVOKE",
      "sender_address": "0x949dfdc3d4e80674592feffb87a05ff76a5012169a781c5e6622b13412fe0",
      "calldata": [
        "0x1",
        "0x949dfdc3d4e80674592feffb87a05ff76a5012169a781c5e6622b13412fe0",
        "0x2a507ab0a32b1a7c2edf394ab941b06593c2a402a5f1a3b9ac3fcb62db0c01a",
        "0x0"
      ],
      "version": "0x100000000000000000000000000000001",
      "signature": [
        "0x1",
        "0x0",
        "0x0"
      ],
      "nonce": "0xfb",
      "max_fee": "0x0"
    }
  ],
  "block_id": "pending",
  "simulation_flags": []
}
 
        41: Transaction execution error: {"transaction_index":0,"execution_error":"reverted: Error in the called contract (0x000949dfdc3d4e80674592feffb87a05ff76a5012169a781c5e6622b13412fe0):\nError at pc=0:20259:\nGot an exception while executing a hint: Custom Hint Error: Execution failed. Failure reason: 0x494e56414c49445f454e545259504f494e54 ('INVALID_ENTRYPOINT').\nCairo traceback (most recent call last):\nUnknown location (pc=0:309)\nUnknown location (pc=0:5819)\nUnknown location (pc=0:11008)\n"}

**Comment by yoga-braavos** [comment]
I see you are able to issue transactions in the account:
https://voyager.online/contract/0x000949dfdc3d4e80674592feffb87a05ff76a5012169a781c5e6622b13412fe0#transactions
