### ISSUE TITLE
Wellet update 

### ISSUE THREAD

**Issue by moonbhai09** [myBraavos/braavos-account-cairo#7]
![Screenshot_2023-05-19-23-42-31-020_com kiwibrowser browser](https://github.com/myBraavos/braavos-account-cairo/assets/77896800/deb3edc8-d03c-4b67-b01c-83ce30474185)
Plz help me to update my wellet

**Comment by moonbhai09** [comment]
![IMG_20230520_014219_855](https://github.com/myBraavos/braavos-account-cairo/assets/77896800/71e9ca73-180d-4735-be01-682d08d0f7ea)
Not showing settings

**Comment by yoga-braavos** [comment]
@moonbhai09 , thanks for the report. Do you also have Desktop / Laptop Chrome? If so, can you upgrade from there?
